### PR TITLE
logins are case insensitive

### PR DESCRIPTION
**Pull request by zwzn**

### CODE REVIEW

**Comment by buckley-w-david** [comment]
Doesn't seem to work for me, getting a 401 response back when trying to login using `ADAM` instead of `adam`
image

**Comment by zwzn** [comment]
apparently when you use `limit` with `collate nocase` it doesn't make things case insensitive. It should work now

**Comment by zwzn** [comment]
on sites i have used it isn't case sensitive. The thing that got me to think of it is if you have a lowercase name you need to uncapitalize the first letter when you are on your phone

**Comment by buckley-w-david** [comment]
I believe if we wanted to help that mobile behaviour then we juautoCapitalize='none'

https://facebook.github.io/react-native/docs/textinput#autocapitalize

I'm not super opinionated on the subject so if you are then I'm fine with going with this, but it does seem like a strange choice to me.

**Pull request merged**
