### PR TITLE
Add guest mode to config

### PR DESCRIPTION
**Pull request by zwzn**

### CODE REVIEW

**Comment by buckley-w-david** [comment]
Just noticed something, not sure if intended or not so I won't revoke my :+1: but I've noticed that as a guest user I still get the settings page as if I was logged in (And as such, can do things like add a user).

Probably not intended.

**Comment by zwzn** [comment]
It doesn't let you change things in the back end but I should reflect that in the front end. I'll hide stuff you can't do

**Comment by zwzn** [comment]
I hid all of the stuff on the settings page when you are a guest

**Comment by buckley-w-david** [comment]
Attempting to do anything while not logged in on this branch is redirecting me to the login page, intended?

**Comment by zwzn** [comment]
Yes. If you don't have `guest: true` in your config it will redirect you as soon as it makes a graphql request

**Comment by buckley-w-david** [comment]
Looks like it's working correctly :+1:

**Pull request merged**
